### ISSUE TITLE
Indentation problem on week 1

### ISSUE THREAD

**Issue by erasta** [PythonFreeCourse/Notebooks#36]
https://github.com/PythonFreeCourse/Notebooks/blob/master/week1/1_Strings_and_Output.ipynb
![image](https://user-images.githubusercontent.com/7118772/93024756-5cc47300-f601-11ea-8ac7-13b578eba8f3.png)

**Comment by yammesicka** [comment]
Hi @erasta,
These are interactive notebooks.
You should follow the instructions on [this](https://www.youtube.com/watch?v=lrUPmBpVQRw) link to install the Jupyter notebook platform, and then download the notebooks from [this](https://github.com/PythonFreeCourse/Notebooks/archive/master.zip) link :)
