### ISSUE TITLE
Hi :)

### ISSUE THREAD

**Issue by idanrl** [PythonFreeCourse/Notebooks#50]
Hi
I want to learn your curse
How do i get invetation?

**Comment by yammesicka** [comment]
Hi :)
Please read the [README.md](https://github.com/PythonFreeCourse/Notebooks#readme) file.
It contains detailed instructions that will help you to set the environment up.

**Comment by idanrl** [comment]
In the movie it says that i supose to get Email with user and password to conect your forum

**Comment by yammesicka** [comment]
The forum is currently closed, and the registration to it is not mandatory :)
