### ISSUE TITLE
Add PEP 8 - Coding style and conventions for Python

### ISSUE THREAD

**Issue by TheSerialiZator** [PythonFreeCourse/Notebooks#52]
** Suggestion. Sorry for opening an issue (and not a PR).

I believe it will be a great idea to add a new chapter for a coding style according to [PEP 8](https://pep8.org/).

Although some projects have their own coding style, it's still important to learn the basics of Python conventions so beginner's code will be much more cleaner and readable for others.

I know you used Python conventions during the course but I think there should be a new whole chapter for this to emphasize this topic.

**Comment by yammesicka** [comment]
Thanks for bringing it up!
Sorry for the extended delay in answering the issue. 
I have been planning the 3rd women course for a while now, and that is taking most of my time :)

I agree that aligning with PEP8 is a great thing to do, and it is unfortunate that we do not currently have any notebooks about it.
While writing a notebook regarding PEP8 is essential, I am afraid it is not currently on my top priority list.
Also, the first weeks are already super tight when thinking about the amount of material we are teaching, so I find it hard to think where it would practically fit in the syllabus.

Currently, my decision (and recommendation for teachers who uses my material) is to teach PEP8 through the code reviews.
Our [lms](https://github.com/PythonFreeCourse/lms) code-checking system does that automatically.
For small classes and in-person education, I would recommend putting less stress on PEP8 when teaching students who have hard times getting started.

- Yam
