### ISSUE TITLE
Week 4, summary issue

### ISSUE THREAD

**Issue by Hadar630** [PythonFreeCourse/Notebooks#60]
Hi, in week 4 summary, there is a hint to make sure you've got the assignment correct, but the hint is wrong

> (Removed solution)

I made sure that 'election_voices' list is correct, i summed up the number of voices in the top of the screenshot.  
here is the code im using:

> (Removed solution)

and i have not received the number `249,333`

**Comment by itraviv** [comment]
the question says "given the dictionary of votes, return the **total number** of votes of those who passed.
you returned the dictionary, not the number.
by the way - if you sum up all the votes in the dictionary: 68582+63702+41075+40144+35830 = 249,333 which is the hint.

please read the instructions carefully, and don't paste solutions to questions in this forum.
