### ISSUE TITLE
שבועות 9-12

### ISSUE THREAD

**Issue by RashtyShahar** [PythonFreeCourse/Notebooks#61]
היי קודם כל תודה הקורס הזה אדיר!רציתי לשאול אם קיימות גם תיקיות לשבועות 9-12 ? אם כן , תוכלו להעלות אותם בבקשה?
תודה!!

**Comment by yammesicka** [comment]
היי :)
אין חומר מסודר זמין כ"כ לשבועות 9–12.
מה שכן זמין אפשר למצוא ב־https://forums.pythonic.guru/.
בהצלחה!
