### ISSUE TITLE
Week 2, lesson 3

### ISSUE THREAD

**Issue by ShirRaj** [PythonFreeCourse/Notebooks#9]
I really like how you explain it. I think something worth mentioning is global.
For 2 reasons: 
1. It'll make the concept clearer 
2. It's important they'll know it's an option (super bad one, but still they might be needing it or just seeing it somewhere)

**Comment by yammesicka** [comment]
While it can make it easier for me to explain things, I do feel it can create bad habits for the students.
I think it's too dangerous to put it as part of the material right now.

**Comment by ShirRaj** [comment]
I agree, didn't think of that aspect.
